modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="doubleedge"
version="1.0.6"
displayName="Double-Edge"
displayURL="https://pigling.itch.io/"
logoFile="logo.png"
credits="This mod was created using MCreator by Pigling "
authors="Pigling"
description="Split tools and armor! Also contains structures and loot."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.doubleedge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration